  server:
    port: 8085

  eureka:
    instance:
      hostname: localhost
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        default-zone: http://localhost:8761/eureka


  spring:
    application:
      name: event-service
    datasource:
      url: "jdbc:mysql://localhost:3306/db?serverTimezone=UTC"
      username: "user"
      password: "password"
      driver-class-name: "com.mysql.cj.jdbc.Driver"  # MySQL driver

    graphql:
      path: /graphql
      graphiql:
        enabled: true


    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
      defer-datasource-initialization: true

    sql:
      init:
        mode: "always"

